### ISSUE TITLE
少年你怎么了。。

### ISSUE THREAD

**Issue by Kinice** [aOrz/vpds#2]
我的timeline里全都是你star这个东西 Orz
![image](https://user-images.githubusercontent.com/11002336/32157941-7eb255ec-bd81-11e7-9431-2195bbd5eaad.png)

**Comment by aOrz** [comment]
哈哈哈哈哈，在开发一个项目获得star或者其他的 issue等操作之后，自动发微信通知的小工具，在做测试。。。。。。

**Comment by Kinice** [comment]
666666

**Comment by aOrz** [comment]
所以有了GitHub 有通知，响应特快

**Comment by Kinice** [comment]
github除了star其他都会发邮件。。

**Comment by aOrz** [comment]
邮件实时性不高，watch 了好多 markdown 仓库，回复太多，早屏蔽了。。。
